security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\Signup: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Signup
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            remember_me:
                secret:   '%kernel.secret%' # required
                lifetime: 604800 # 1 week in seconds
            form_login:
                login_path: log
                check_path: log
                default_target_path: /log
            logout:
                path: logout
                target: /log

    access_control:
    # - { path: ^/gestion, roles: ROLE_ADMIN }
    # - { path: ^/back/ticket, roles: [ROLE_ADMIN, ROLE_MODO] }

    role_hierarchy:
        ROLE_VISITOR:     ROLE_ALLOWED_TO_SWITCH
        ROLE_ADHERENT:    [ROLE_VISITOR]
        ROLE_MODO:        [ROLE_ADHERENT, ROLE_VISITOR]
        ROLE_ADMIN:       [ROLE_MODO, ROLE_ADHERENT, ROLE_VISITOR]

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
