<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container61mjXsm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container61mjXsm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container61mjXsm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container61mjXsm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container61mjXsm\App_KernelDevDebugContainer([
    'container.build_hash' => '61mjXsm',
    'container.build_id' => '586d5d8c',
    'container.build_time' => 1738337192,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container61mjXsm');
